spring:
  data:
    mongodb:
      uri: mongodb://root:rootUser@localhost:27017/payment?authSource=admin
      username: root
      password: rootUser
      auto-index-creation: true
server:
  port: 9000